# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.7.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal git-r3

DESCRIPTION="Retrie integration plugin for Haskell Language Server"
HOMEPAGE="https://hackage.haskell.org/package/hls-retrie-plugin"
EGIT_REPO_URI="https://github.com/haskell/haskell-language-server.git"

LICENSE="Apache-2.0"
SLOT="0/${PV}"
KEYWORDS=""

S="${S}/plugins/${PN}"

RDEPEND="dev-haskell/aeson:=[profile?]
	dev-haskell/extra:=[profile?]
	~dev-haskell/ghcide-0.7.2.9999:=[profile?]
	dev-haskell/hashable:=[profile?]
	dev-haskell/haskell-lsp:=[profile?]
	dev-haskell/haskell-lsp-types:=[profile?]
	~dev-haskell/hls-plugin-api-0.6.0.9999:=[profile?]
	>=dev-haskell/retrie-0.1.1.0:=[profile?]
	dev-haskell/safe-exceptions:=[profile?]
	dev-haskell/shake:=[profile?]
	dev-haskell/text:=[profile?]
	dev-haskell/unordered-containers:=[profile?]
	>=dev-lang/ghc-8.6.3:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.4.0.1
"
