# Copyright 1999-2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.7.9999
#hackport: flags: -pedantic

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal git-r3

DESCRIPTION="Hlint integration plugin with Haskell Language Server"
HOMEPAGE="https://hackage.haskell.org/package/hls-hlint-plugin"
EGIT_REPO_URI="https://github.com/haskell/haskell-language-server.git"

LICENSE="Apache-2.0"
SLOT="0/${PV}"
KEYWORDS=""
IUSE="ghc-lib"

S="${S}/plugins/${PN}"

RDEPEND="dev-haskell/aeson:=[profile?]
	>=dev-haskell/apply-refact-0.9.0.0:=[profile?]
	dev-haskell/data-default:=[profile?]
	dev-haskell/diff:=[profile?]
	dev-haskell/extra:=[profile?]
	~dev-haskell/ghc-exactprint-0.6.3.9999:=[profile?]
	~dev-haskell/ghcide-0.7.2.9999:=[profile?,ghc-lib?]
	dev-haskell/hashable:=[profile?]
	dev-haskell/haskell-lsp:=[profile?]
	>=dev-haskell/hlint-3.2:=[profile?]
	~dev-haskell/hls-plugin-api-0.6.0.9999:=[profile?]
	dev-haskell/hslogger:=[profile?]
	dev-haskell/lens:=[profile?]
	dev-haskell/regex-tdfa:=[profile?]
	dev-haskell/shake:=[profile?]
	dev-haskell/temporary:=[profile?]
	dev-haskell/text:=[profile?]
	dev-haskell/unordered-containers:=[profile?]
	>=dev-lang/ghc-8.6.3:=
	ghc-lib? ( >=dev-haskell/ghc-lib-8.10.2.20200916:=[profile?] <dev-haskell/ghc-lib-8.11:=[profile?]
		>=dev-haskell/ghc-lib-parser-ex-8.10:=[profile?] <dev-haskell/ghc-lib-parser-ex-8.11:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.4.0.1
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag ghc-lib ghc-lib) \
		--flag=-pedantic
}
